reload haproxy when yaml changes are detected

diff --git a/root/etc/s6-overlay/s6-rc.d/haproxy/run b/root/etc/s6-overlay/s6-rc.d/haproxy/run
--- a/root/etc/s6-overlay/s6-rc.d/haproxy/run
+++ b/root/etc/s6-overlay/s6-rc.d/haproxy/run
@@ -40,3 +40,17 @@ else
     echo "[Haproxy] is already running." | ts '%Y-%m-%d %H:%M:%S'
     exit 0
 fi
+
+# Watch for changes in the haproxy configuration file
+echo "[Haproxy] is monitoring your haproxy.yaml file for changes, if changes are detected we will reload without restarting" | ts '%Y-%m-%d %H:%M:%S'
+exec s6-setuidgid acme inotifywait -m "$HAPROXY_YAML" -e modify | while read -r file; do
+    echo "[Haproxy] detected changes to ${file}, reloading haproxy..." | ts '%Y-%m-%d %H:%M:%S'
+    
+    # Run the reload script
+    if /scripts/reload-haproxy.sh; then
+        echo "[Haproxy] reload successful" | ts '%Y-%m-%d %H:%M:%S'
+    else
+        EXIT_CODE=$?
+        echo "[Haproxy] reload failed with exit code ${EXIT_CODE}" | ts '%Y-%m-%d %H:%M:%S'
+    fi
+done
