lots of changes
* removed brotli not supported
* removed deploy cert after issuing cert, too many reload issues
* moved haproxy script generation into acme long run process

diff --git a/root/etc/s6-overlay/s6-rc.d/acme/run b/root/etc/s6-overlay/s6-rc.d/acme/run
--- a/root/etc/s6-overlay/s6-rc.d/acme/run
+++ b/root/etc/s6-overlay/s6-rc.d/acme/run
@@ -42,7 +42,6 @@ function check_for_missing_domain_certs() {
     # Loop through the domains and process them
     for domain in "${domains[@]}"; do
         debug_log "Processing domain: $domain" | ts '%Y-%m-%d %H:%M:%S'
-        
         {
             if [ -f "${HAPROXY_CERTS_DIR}/${domain}.pem" ]; then
                 debug_log "Certificate for $domain is deployed in haproxy" | ts '%Y-%m-%d %H:%M:%S'
@@ -87,4 +86,16 @@ echo "[acme] is monitoring your haproxy.yaml file for changes, if changes are de
 exec s6-setuidgid acme inotifywait -m "$HAPROXY_YAML" -e modify | while read -r file; do
     echo "[acme] detected changes to ${file}, looking for new domains..." | ts '%Y-%m-%d %H:%M:%S'
     check_for_missing_domain_certs;
+
+    # regenerate the cfg file
+    echo "[acme] generating new haproxy cfg and reloading haproxy..." | ts '%Y-%m-%d %H:%M:%S'
+    s6-setuidgid acme /scripts/generate_haproxy_config.sh;
+    
+    # Run the reload script
+    if s6-setuidgid haproxy /scripts/reload-haproxy.sh; then
+        echo "[acme] haproxy reloading successful" | ts '%Y-%m-%d %H:%M:%S'
+    else
+        EXIT_CODE=$?
+        echo "[acme] haproxy reload failed with exit code ${EXIT_CODE}" | ts '%Y-%m-%d %H:%M:%S'
+    fi
 done
